### ISSUE TITLE
DNS NAPTR record Service field is compared in Case Sensitive manner

### ISSUE THREAD

**Issue by gkumar78** [RestComm/jain-sip.ext#1]
Recently noticed that DefaultDNSLookupPerformer class of this Mobicents extension is comparing Service field of returned NAPTR RRs with defined Service protocols of "D2U" and "D2T" in case-sensitive manner. Hence, when returned NAPTR records have lowercase values in Service fields ("SIP+d2t" or "sip+d2u"), they result in a mismatch and ignored for further SRV lookup. 

However, the base NAPTR RR RFC 2915 indicates in Section 2, Page 6 that the case of the alphabetic characters is not significant for Service field value. Hence, SIP+D2U should be treated same as sip+d2u.

**Comment by deruelle** [comment]
Thanks for reporting it. Can you contribute a fix for this and do a Pull Request ?

**Comment by gkumar78** [comment]
I have proposed fix for this with Pull request. Please check

**Comment by deruelle** [comment]
Ah great didn't see it before, sorry about that. Can you sign the contributor license agreement at http://www.telestax.com/open-source-2/#Contribute so we can accept the Pull Request ?

Thanks in advance

**Comment by deruelle** [comment]
Let me know when you had time to sign the CLA so that we can accept the contribution. Thanks

**Comment by gkumar78** [comment]
I have signed Corporate CLA as Infosys Developer in name of Girish Kumar. Hope you can accept the patch now

**Comment by deruelle** [comment]
Thanks I have accepted the pull request. Do you want to be acknowledged at http://www.telestax.com/open-source-2/acknowledgments/- ? If so do you want me to link to your  linkedin profile ?

**Comment by deruelle** [comment]
Acknowledged at http://www.telestax.com/open-source-2/acknowledgments/
